### ISSUE TITLE
Application provided invalid, non monotonically increasing dts to muxer in stream 0: 619 >= 619

### ISSUE THREAD

**Issue by TankZhouFirst** [laomao0/BIN#1]
when i generating dataset using script create_dataset_blur_N_frames_average_Adobe.sh, it appears message as follow:
`Application provided invalid, non monotonically increasing dts to muxer in stream 0: 619 >= 619`
does it matter?

PS: some modifies:

1. move scripts from data_scripts/adobe240fps to data_scripts
2. change line 192 in create_dataset_blur_N_frames_average.py as follow:
`
f = open(args.dataset[:-5] + '/test_list.txt', "r" )
`

**Comment by laomao0** [comment]
It does not matter.

**Comment by TankZhouFirst** [comment]
> It does not matter.

Thanks
