### ISSUE TITLE
A Question about generating blurry frames

### ISSUE THREAD

**Issue by linkboyx** [laomao0/BIN#5]
Noticed that in your paper, when generating blurry frames, parameter K = 8 and tao = 5. Thus, the resulting blurry frame has 3 high-fps frames overlapped with its last/next blurry frame.  Why does it need 'overlap'? Is there any consideration of this design? Thank you.

**Comment by laomao0** [comment]
Yes, the overlap does exist. Because the tao can adjust the blurry degree of the synthesized frames. Choosing a small tao, for example, tao = 3, making the synthesized video not too blurry (e.g., PSNR > 30dB).
